### PR TITLE
Make `TimestampStr`'s length statically available

### PR DESCRIPTION
**Pull request by robertbastian**

### CODE REVIEW

**Comment by novacrazy** [comment]
This isn't always accurate to the length of the formatted string due to the sign being omitted if positive. As implemented here it's basically equivalent to `mem::size_of`. Could be made into a const function that checks the first byte, though?

**Comment by robertbastian** [comment]
Yeah I've realised that. I guess if you know you're not handling negative years, you can use `::LEN - 1` as the static length. Making this a const function does not help me, because it's not possible to const-construct a `TimestampStr`.

**Comment by novacrazy** [comment]
What is your use case? Could `mem::size_of` work instead? I could also look into supporting const-formatting eventually.

**Comment by robertbastian** [comment]
I want to const-compute the length of a HTTP message I'm assembling. I could just hardcode the number but that seems brittle.

`mem::size_of` is the size of the `TimestampStr` struct. There's no guarantee that that matches the length of the derefed `&str`.

**Comment by novacrazy** [comment]
`TimestampStr` is just `TimestampStr([u8; LEN])`, and will be the same size in bytes as its max length. `mem::size_of::<TimestampStr>() == TimestampStr::LEN`. It's just that it will be `LEN - 1` as a `&str` upon deref if positive, both approaches have that same downside but equivalent values.

I'm not fully comfortable exposing a `LEN` const due to that sign part, as it could be misleading. 

I'll try to think up a more convenient solution soon. Honestly maybe just naming it `MAX_LEN` instead.

**Comment by novacrazy** [comment]
I added `TimestampStr::MAX_LEN` to 0.2.17

**Comment by robertbastian** [comment]
Thanks!

**Pull request closed without merging**
